// Generated by uniffi-bindgen-react-native, then hand-wired.
//
// NOTE: `ubrn generate bindings` only writes cpp/generated/*. The turbo-module
// glue (this file) comes from `generate turbo-module`, so when you regenerate
// bindings alone you get an EMPTY installRustCrate and the JS side fails with
// "Cannot read property 'ubrn_ffi_<crate>_uniffi_contract_version' of undefined".
#include "mopro-ffi.h"
#include "generated/prover.hpp"

namespace moproffi {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeProver::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		NativeProver::unregisterModule(runtime);
		return true;
	}
}
